# JPype Release pipeline
trigger: none
pr: 
  branches:
    include:
    -  releases/*
  paths:
    include:
    - .bumpversion.cfg
    - .azure/release.yml

variables:
  package_name: JPype1

stages:
- stage: Initial
  jobs:
  - job: SourceDistribution
    pool: 
      vmImage: "ubuntu-16.04"
    steps:
    - template: scripts/sdist.yml
    - template: scripts/ivy.yml

- stage: Package
  jobs:
  # From https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/
  - job: ManyLinux
    condition: eq(1,1)
    strategy:
      matrix:
        64Bit2014:
          arch: aarch64
          plat: manylinux2014_aarch64
          image: quay.io/pypa/manylinux2014_aarch64
          python.architecture: aarch64
        64Bit:
          arch: x86_64
          plat: manylinux1_x86_64
          image: quay.io/pypa/manylinux1_x86_64
          python.architecture: x64
    pool:
      vmImage: "ubuntu-16.04"
    steps:
    - template: scripts/deps.yml
    - template: scripts/wheels-linux.yml
    - template: scripts/publish-dist.yml
